In [5]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import fastai

from sklearn import metrics
from fastai.imports import *
from fastai.structured import *

from pandas_summary import DataFrameSummary
from sklearn.ensemble import RandomForestRegressor , RandomForestClassifier
import re
import seaborn as sns

from sklearn import metrics
import io
import xgboost as xgb

In [7]:
PATH = './data/'
!ls {PATH}

sample_submission.csv  test.csv  train.csv

In [8]:
train_raw = pd.read_csv(f'{PATH}train.csv',low_memory=False,parse_dates=['opened_at'])
test_raw = pd.read_csv(f'{PATH}test.csv',low_memory=False,parse_dates=['opened_at'])

In [9]:
train_raw.T

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062,INC0000063,INC0000064,INC0000065,INC0000066,INC0000067,...,INC0028188,INC0028190,INC0028191,INC0028192,INC0028193,INC0028195,INC0028196,INC0028200,INC0028201,INC0028203
reassignment_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reopen_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
update_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,Opened by 8,Opened by 397,Opened by 8,Opened by 180,Opened by 180,Opened by 180,Opened by 131,Opened by 131,Opened by 24,Opened by 180,...,Opened by 24,Opened by 301,Opened by 131,Opened by 62,Opened by 24,Opened by 17,Opened by 17,Opened by 24,Opened by 24,Opened by 55
opened_at,2016-02-29 01:16:00,2016-02-29 04:40:00,2016-02-29 06:10:00,2016-02-29 06:38:00,2016-02-29 06:58:00,2016-02-29 07:08:00,2016-02-29 07:10:00,2016-02-29 07:38:00,2016-02-29 08:03:00,2016-02-29 08:03:00,...,2016-05-11 08:41:00,2016-05-11 08:41:00,2016-05-11 08:42:00,2016-05-11 08:44:00,2016-05-11 08:44:00,2016-05-11 08:45:00,2016-05-11 08:46:00,2016-05-11 08:50:00,2016-05-11 08:51:00,2016-05-11 08:52:00
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,Location 143,Location 165,Location 204,Location 204,Location 93,Location 93,Location 143,Location 108,Location 161,Location 143,...,Location 161,Location 56,Location 161,Location 143,Location 108,Location 204,Location 93,Location 97,Location 51,Location 204
category,Category 55,Category 40,Category 20,Category 9,Category 53,Category 20,Category 53,Category 44,Category 55,Category 9,...,Category 9,Category 37,Category 42,Category 53,Category 20,Category 42,Category 37,Category 42,Category 53,Category 26
subcategory,Subcategory 170,Subcategory 215,Subcategory 125,Subcategory 97,Subcategory 168,Subcategory 125,Subcategory 168,Subcategory 229,Subcategory 185,Subcategory 110,...,Subcategory 164,Subcategory 123,Subcategory 223,Subcategory 303,Subcategory 174,Subcategory 223,Subcategory 174,Subcategory 223,Subcategory 130,Subcategory 275
impact,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,...,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium
urgency,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,...,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium
priority,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,...,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate
assigned_to,NaN,Resolver 89,NaN,Resolver 125,NaN,NaN,Resolver 78,Resolver 216,NaN,Resolver 236,...,Resolver 24,Resolver 82,Resolver 194,Resolver 33,Resolver 93,Resolver 13,Resolver 83,Resolver 17,NaN,NaN
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,...,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify
vendor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
target_days,5,6,5,7,5,5,8,7,7,7,...,6,217,5,5,6,5,5,5,11,5

In [10]:
def extracting_num(df_raw):
  df = df_raw.copy()
  df['opened_by'] = df['opened_by'].str.split(expand=True)[2]
  df['location'] = df['location'].str.split(expand=True)[1]
  df['category'] = df['category'].str.split(expand=True)[1]
  df['subcategory'] = df['subcategory'].str.split(expand=True)[1]
  df['impact'] = df['impact'].str.split(expand=True)[0]
  df['urgency'] = df['urgency'].str.split(expand=True)[0]
  df['priority'] = df['priority'].str.split(expand=True)[0]
  df['assigned_to'] = df['assigned_to'].str.split(expand=True)[1]
  return df

In [11]:
train_raw = extracting_num(train_raw)

In [12]:
train_raw.T

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062,INC0000063,INC0000064,INC0000065,INC0000066,INC0000067,...,INC0028188,INC0028190,INC0028191,INC0028192,INC0028193,INC0028195,INC0028196,INC0028200,INC0028201,INC0028203
reassignment_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reopen_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
update_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,8,397,8,180,180,180,131,131,24,180,...,24,301,131,62,24,17,17,24,24,55
opened_at,2016-02-29 01:16:00,2016-02-29 04:40:00,2016-02-29 06:10:00,2016-02-29 06:38:00,2016-02-29 06:58:00,2016-02-29 07:08:00,2016-02-29 07:10:00,2016-02-29 07:38:00,2016-02-29 08:03:00,2016-02-29 08:03:00,...,2016-05-11 08:41:00,2016-05-11 08:41:00,2016-05-11 08:42:00,2016-05-11 08:44:00,2016-05-11 08:44:00,2016-05-11 08:45:00,2016-05-11 08:46:00,2016-05-11 08:50:00,2016-05-11 08:51:00,2016-05-11 08:52:00
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,143,165,204,204,93,93,143,108,161,143,...,161,56,161,143,108,204,93,97,51,204
category,55,40,20,9,53,20,53,44,55,9,...,9,37,42,53,20,42,37,42,53,26
subcategory,170,215,125,97,168,125,168,229,185,110,...,164,123,223,303,174,223,174,223,130,275
impact,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
urgency,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
priority,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
assigned_to,NaN,89,NaN,125,NaN,NaN,78,216,NaN,236,...,24,82,194,33,93,13,83,17,NaN,NaN
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,...,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify
vendor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
target_days,5,6,5,7,5,5,8,7,7,7,...,6,217,5,5,6,5,5,5,11,5

In [13]:
train_raw.drop(columns='vendor',inplace=True)
train_raw.drop(columns='reassignment_count',inplace=True)
train_raw.drop(columns='reopen_count',inplace=True)
train_raw.drop(columns='update_count',inplace=True)

In [14]:
train_raw.T

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062,INC0000063,INC0000064,INC0000065,INC0000066,INC0000067,...,INC0028188,INC0028190,INC0028191,INC0028192,INC0028193,INC0028195,INC0028196,INC0028200,INC0028201,INC0028203
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,8,397,8,180,180,180,131,131,24,180,...,24,301,131,62,24,17,17,24,24,55
opened_at,2016-02-29 01:16:00,2016-02-29 04:40:00,2016-02-29 06:10:00,2016-02-29 06:38:00,2016-02-29 06:58:00,2016-02-29 07:08:00,2016-02-29 07:10:00,2016-02-29 07:38:00,2016-02-29 08:03:00,2016-02-29 08:03:00,...,2016-05-11 08:41:00,2016-05-11 08:41:00,2016-05-11 08:42:00,2016-05-11 08:44:00,2016-05-11 08:44:00,2016-05-11 08:45:00,2016-05-11 08:46:00,2016-05-11 08:50:00,2016-05-11 08:51:00,2016-05-11 08:52:00
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,143,165,204,204,93,93,143,108,161,143,...,161,56,161,143,108,204,93,97,51,204
category,55,40,20,9,53,20,53,44,55,9,...,9,37,42,53,20,42,37,42,53,26
subcategory,170,215,125,97,168,125,168,229,185,110,...,164,123,223,303,174,223,174,223,130,275
impact,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
urgency,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
priority,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
assigned_to,NaN,89,NaN,125,NaN,NaN,78,216,NaN,236,...,24,82,194,33,93,13,83,17,NaN,NaN
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,...,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify
target_days,5,6,5,7,5,5,8,7,7,7,...,6,217,5,5,6,5,5,5,11,5

In [15]:
train_raw['assigned_to'].count()

14591

In [16]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
train_raw['notify']= labelencoder.fit_transform(train_raw['notify'])

In [17]:
df = pd.DataFrame(train_raw['assigned_to'])

In [18]:
train_raw['assigned_to']=df.fillna(180)
train_raw['opened_by']=df.fillna(180)
train_raw['location']=df.fillna(143)
train_raw['category']=df.fillna(20)
train_raw['subcategory']=df.fillna(125)

In [19]:
train_raw.T

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062,INC0000063,INC0000064,INC0000065,INC0000066,INC0000067,...,INC0028188,INC0028190,INC0028191,INC0028192,INC0028193,INC0028195,INC0028196,INC0028200,INC0028201,INC0028203
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,180,89,180,125,180,180,78,216,180,236,...,24,82,194,33,93,13,83,17,180,180
opened_at,2016-02-29 01:16:00,2016-02-29 04:40:00,2016-02-29 06:10:00,2016-02-29 06:38:00,2016-02-29 06:58:00,2016-02-29 07:08:00,2016-02-29 07:10:00,2016-02-29 07:38:00,2016-02-29 08:03:00,2016-02-29 08:03:00,...,2016-05-11 08:41:00,2016-05-11 08:41:00,2016-05-11 08:42:00,2016-05-11 08:44:00,2016-05-11 08:44:00,2016-05-11 08:45:00,2016-05-11 08:46:00,2016-05-11 08:50:00,2016-05-11 08:51:00,2016-05-11 08:52:00
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,143,89,143,125,143,143,78,216,143,236,...,24,82,194,33,93,13,83,17,143,143
category,20,89,20,125,20,20,78,216,20,236,...,24,82,194,33,93,13,83,17,20,20
subcategory,125,89,125,125,125,125,78,216,125,236,...,24,82,194,33,93,13,83,17,125,125
impact,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
urgency,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
priority,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
assigned_to,180,89,180,125,180,180,78,216,180,236,...,24,82,194,33,93,13,83,17,180,180
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
target_days,5,6,5,7,5,5,8,7,7,7,...,6,217,5,5,6,5,5,5,11,5

In [20]:
# for index,row in train_raw.iterrows() :
#     if(row['target_days']>10):
#         train_raw.drop(index,inplace=True)

In [24]:
df = train_raw.copy()
add_datepart(df,'opened_at')
df.T

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062,INC0000063,INC0000064,INC0000065,INC0000066,INC0000067,...,INC0028188,INC0028190,INC0028191,INC0028192,INC0028193,INC0028195,INC0028196,INC0028200,INC0028201,INC0028203
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,180,89,180,125,180,180,78,216,180,236,...,24,82,194,33,93,13,83,17,180,180
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,143,89,143,125,143,143,78,216,143,236,...,24,82,194,33,93,13,83,17,143,143
category,20,89,20,125,20,20,78,216,20,236,...,24,82,194,33,93,13,83,17,20,20
subcategory,125,89,125,125,125,125,78,216,125,236,...,24,82,194,33,93,13,83,17,125,125
impact,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
urgency,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
priority,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
assigned_to,180,89,180,125,180,180,78,216,180,236,...,24,82,194,33,93,13,83,17,180,180
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
target_days,5,6,5,7,5,5,8,7,7,7,...,6,217,5,5,6,5,5,5,11,5
opened_atYear,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,...,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
opened_atMonth,2,2,2,2,2,2,2,2,2,2,...,5,5,5,5,5,5,5,5,5,5
opened_atWeek,9,9,9,9,9,9,9,9,9,9,...,19,19,19,19,19,19,19,19,19,19
opened_atDay,29,29,29,29,29,29,29,29,29,29,...,11,11,11,11,11,11,11,11,11,11
opened_atDayofweek,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
opened_atDayofyear,60,60,60,60,60,60,60,60,60,60,...,132,132,132,132,132,132,132,132,132,132
opened_atIs_month_end,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_month_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atElapsed,1456708560,1456720800,1456726200,1456727880,1456729080,1456729680,1456729800,1456731480,1456732980,1456732980,...,1462956060,1462956060,1462956120,1462956240,1462956240,1462956300,1462956360,1462956600,1462956660,1462956720

In [25]:
df['target_days'].value_counts()

5      8881
6      1276
7       878
8       731
10      712
       ...
178       1
165       1
146       1
170       1
162       1
Name: target_days, Length: 231, dtype: int64

In [26]:
df.drop(columns='Id',inplace=True)

In [27]:
df.drop(columns='opened_atYear',inplace=True)
df.drop(columns='made_sla',inplace=True)
df.drop(columns='impact',inplace=True)
df.drop(columns='urgency',inplace=True)
df.drop(columns='opened_atIs_year_start',inplace=True)
df.drop(columns='opened_atIs_year_end',inplace=True)

In [28]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
opened_by,180,89,180,125,180,180,78,216,180,236,...,24,82,194,33,93,13,83,17,180,180
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,143,89,143,125,143,143,78,216,143,236,...,24,82,194,33,93,13,83,17,143,143
category,20,89,20,125,20,20,78,216,20,236,...,24,82,194,33,93,13,83,17,20,20
subcategory,125,89,125,125,125,125,78,216,125,236,...,24,82,194,33,93,13,83,17,125,125
priority,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
assigned_to,180,89,180,125,180,180,78,216,180,236,...,24,82,194,33,93,13,83,17,180,180
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
target_days,5,6,5,7,5,5,8,7,7,7,...,6,217,5,5,6,5,5,5,11,5
opened_atMonth,2,2,2,2,2,2,2,2,2,2,...,5,5,5,5,5,5,5,5,5,5
opened_atWeek,9,9,9,9,9,9,9,9,9,9,...,19,19,19,19,19,19,19,19,19,19
opened_atDay,29,29,29,29,29,29,29,29,29,29,...,11,11,11,11,11,11,11,11,11,11
opened_atDayofweek,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
opened_atDayofyear,60,60,60,60,60,60,60,60,60,60,...,132,132,132,132,132,132,132,132,132,132
opened_atIs_month_end,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_month_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atElapsed,1456708560,1456720800,1456726200,1456727880,1456729080,1456729680,1456729800,1456731480,1456732980,1456732980,...,1462956060,1462956060,1462956120,1462956240,1462956240,1462956300,1462956360,1462956600,1462956660,1462956720

In [29]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [30]:
df['knowledge']= label_encoder.fit_transform(df['knowledge'])
df['opened_atIs_month_end']= label_encoder.fit_transform(df['opened_atIs_month_end'])
df['opened_atIs_month_start']= label_encoder.fit_transform(df['opened_atIs_month_start'])
df['opened_atIs_quarter_end']= label_encoder.fit_transform(df['opened_atIs_quarter_end'])
df['opened_atIs_quarter_start']= label_encoder.fit_transform(df['opened_atIs_quarter_start'])
df['contact_type']= label_encoder.fit_transform(df['contact_type'])

In [31]:
df.isnull().sum()

opened_by                    0
contact_type                 0
location                     0
category                     0
subcategory                  0
priority                     0
assigned_to                  0
knowledge                    0
notify                       0
target_days                  0
opened_atMonth               0
opened_atWeek                0
opened_atDay                 0
opened_atDayofweek           0
opened_atDayofyear           0
opened_atIs_month_end        0
opened_atIs_month_start      0
opened_atIs_quarter_end      0
opened_atIs_quarter_start    0
opened_atElapsed             0
dtype: int64

In [32]:
X = df.copy()

In [33]:
X.drop(columns='target_days',inplace=True)

In [34]:
y = df['target_days']

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [36]:
def print_score(m):
    print(metrics.mean_absolute_error(m.predict(X_train),y_train),metrics.mean_absolute_error(m.predict(X_valid),y_valid))

In [37]:
from sklearn.neighbors import KNeighborsClassifier
n = KNeighborsClassifier()
n.fit(X_train,y_train)
print_score(n)

6.8000625 6.86225

In [38]:
from sklearn.ensemble import RandomForestRegressor , RandomForestClassifier
m = RandomForestClassifier(n_jobs=-1,random_state=3,min_samples_leaf=1)
m.fit(X_train,y_train)
print_score(m)

/home/vaibhav/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

0.9449375 8.2245

In [41]:
k = RandomForestRegressor(n_jobs=-1,random_state=3,min_samples_leaf=1)
k.fit(X_train,y_train)
print_score(k)

/home/vaibhav/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

3.394542544642857 8.520095376984125

In [40]:
# import xgboost as xgb
# xg_reg = xgb.XGBClassifier(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
#                 max_depth = 5, alpha = 10, n_estimators = 50)
# xg_reg.fit(X_train,y_train)
# print_score(xg_reg)

ValueError: DataFrame.dtypes for data must be int, float or bool.
                Did not expect the data types in fields opened_by, location, category, subcategory, priority, assigned_to