# DATAQUEST

In [311]:
%reload_ext autoreload
%autoreload 2

%matplotlib inline

## Installing fastai==0.7.0

In [312]:
# !pip install fastai==0.7.0

## Importing libraries

In [313]:
from fastai.imports import *
from fastai.structured import *

from pandas_summary import DataFrameSummary
from sklearn.ensemble import RandomForestRegressor , RandomForestClassifier
import re
import seaborn as sns

from sklearn import metrics
import io
import xgboost as xgb

## Getting the data in Google Colab

In [314]:
PATH = './data/'
!ls {PATH}

sample_submission.csv  test.csv  train.csv

In [315]:
train_raw = pd.read_csv(f'{PATH}train.csv',low_memory=False,parse_dates=['opened_at'])

In [316]:
test_raw = pd.read_csv(f'{PATH}test.csv',low_memory=False,parse_dates=['opened_at'])

## Setting some lists to measure progress

In [317]:
train_map = []
test_map = []

##  Fuctions

In [318]:
def display_all(df):
    with pd.option_context("display.max_rows", 1000, "display.max_columns", 1000): 
        display(df)

In [319]:
def print_score(m):
    print(metrics.mean_absolute_error(m.predict(X_train),y_train),metrics.mean_absolute_error(m.predict(X_valid),y_valid))

In [320]:
def put_in_metrics(n):
    train_map.append(metrics.mean_absolute_error(n.predict(X_train),y_train))
    test_map.append(metrics.mean_absolute_error(n.predict(X_valid),y_valid))

In [321]:
def split_vals(a,n): return a[:n].copy() , a[n:].copy()

In [322]:
def extracting_num(df_raw):
  df = df_raw.copy()
  df['opened_by'] = df['opened_by'].str.split(expand=True)[2]
  df['location'] = df['location'].str.split(expand=True)[1]
  df['category'] = df['category'].str.split(expand=True)[1]
  df['subcategory'] = df['subcategory'].str.split(expand=True)[1]
  df['impact'] = df['impact'].str.split(expand=True)[0]
  df['urgency'] = df['urgency'].str.split(expand=True)[0]
  df['priority'] = df['priority'].str.split(expand=True)[0]
  return df

## EDA (DATA PREPROCESSING)

In [323]:
train_raw.head().T

,0,1,2,3,4
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062
reassignment_count,0,0,0,0,0
reopen_count,0,0,0,0,0
update_count,0,0,0,0,0
made_sla,True,True,True,True,True
opened_by,Opened by 8,Opened by 397,Opened by 8,Opened by 180,Opened by 180
opened_at,2016-02-29 01:16:00,2016-02-29 04:40:00,2016-02-29 06:10:00,2016-02-29 06:38:00,2016-02-29 06:58:00
contact_type,Phone,Phone,Phone,Phone,Phone
location,Location 143,Location 165,Location 204,Location 204,Location 93
category,Category 55,Category 40,Category 20,Category 9,Category 53
subcategory,Subcategory 170,Subcategory 215,Subcategory 125,Subcategory 97,Subcategory 168
impact,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium
urgency,2 - Medium,2 - Medium,2 - Medium,2 - Medium,2 - Medium
priority,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate,3 - Moderate
assigned_to,NaN,Resolver 89,NaN,Resolver 125,NaN
knowledge,True,True,True,True,True
notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify
vendor,NaN,NaN,NaN,NaN,NaN
target_days,5,6,5,7,5

In [324]:
train_raw = extracting_num(train_raw)

In [325]:
train_raw.T

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062,INC0000063,INC0000064,INC0000065,INC0000066,INC0000067,...,INC0028188,INC0028190,INC0028191,INC0028192,INC0028193,INC0028195,INC0028196,INC0028200,INC0028201,INC0028203
reassignment_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reopen_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
update_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,8,397,8,180,180,180,131,131,24,180,...,24,301,131,62,24,17,17,24,24,55
opened_at,2016-02-29 01:16:00,2016-02-29 04:40:00,2016-02-29 06:10:00,2016-02-29 06:38:00,2016-02-29 06:58:00,2016-02-29 07:08:00,2016-02-29 07:10:00,2016-02-29 07:38:00,2016-02-29 08:03:00,2016-02-29 08:03:00,...,2016-05-11 08:41:00,2016-05-11 08:41:00,2016-05-11 08:42:00,2016-05-11 08:44:00,2016-05-11 08:44:00,2016-05-11 08:45:00,2016-05-11 08:46:00,2016-05-11 08:50:00,2016-05-11 08:51:00,2016-05-11 08:52:00
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,143,165,204,204,93,93,143,108,161,143,...,161,56,161,143,108,204,93,97,51,204
category,55,40,20,9,53,20,53,44,55,9,...,9,37,42,53,20,42,37,42,53,26
subcategory,170,215,125,97,168,125,168,229,185,110,...,164,123,223,303,174,223,174,223,130,275
impact,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
urgency,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
priority,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
assigned_to,NaN,Resolver 89,NaN,Resolver 125,NaN,NaN,Resolver 78,Resolver 216,NaN,Resolver 236,...,Resolver 24,Resolver 82,Resolver 194,Resolver 33,Resolver 93,Resolver 13,Resolver 83,Resolver 17,NaN,NaN
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,...,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify
vendor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
target_days,5,6,5,7,5,5,8,7,7,7,...,6,217,5,5,6,5,5,5,11,5

In [326]:
display_all(train_raw.isna().sum().sort_index())

Id                        0
assigned_to            5409
category                 26
contact_type              0
impact                    0
knowledge                 0
location                 52
made_sla                  0
notify                    0
opened_at                 0
opened_by               714
priority                  0
reassignment_count        0
reopen_count              0
subcategory              56
target_days               0
update_count              0
urgency                   0
vendor                19994
dtype: int64

##### The attributes like impact , priority , urgency have similar kind of behaviour in general. We could test this out by making graph. The graph should be Id vs the attributes in ascending order(in order).

In [327]:
train_raw['priority'].value_counts()

3    18987
4      611
2      251
1      151
Name: priority, dtype: int64

In [328]:
train_raw['impact'].value_counts()

2    19174
3      599
1      227
Name: impact, dtype: int64

In [329]:
train_raw['urgency'].value_counts()

2    19117
3      557
1      326
Name: urgency, dtype: int64

##  Dropping columns (based on their interdependecy and not use)

In [330]:
column_names = ['Id','vendor']

In [331]:
train_raw.drop(columns='vendor',inplace=True)

## Removing outliers

#### Outliers in update_count, opened_by

In [332]:
train_raw.drop(train_raw[train_raw['update_count'] !=0].index,inplace=True)

In [333]:
train_raw.update_count.value_counts()

0    19995
Name: update_count, dtype: int64

####  The columns opened_by,location,category,subcategory can be made integer directly by stripping away the alphacharacters .  The columns impact,urgency,priority could be splitted.

In [334]:
add_datepart(train_raw,'opened_at')

In [335]:
for index,row in train_raw.iterrows() :
    if(row['target_days']>10):
        train_raw.drop(index,inplace=True)

## Splitting column data

In [336]:
# train_raw['opened_by'] = train_raw['opened_by'].str.split(expand=True)[2]
#  train_raw.opened_by.astype('int')

In [337]:
# train_raw['opened_by'].isnull().sum()

In [338]:
# train_raw.dtypes

In [339]:
# train_raw.opened_by.astype('int',errors='ignore')

In [340]:
# train_raw['opened_by_na'] = train_raw['opened_by'].copy().isna()

In [341]:
# train_raw[train_raw['opened_by'].isna()] = 0

In [342]:
# train_raw.opened_by_na.value_counts()

#### Now since we have many null values and we got to deal with that. We could do one hot encoding . Make a column of opened_by_na and then give 1 to value having NaN values and 0 to rest . And then in opened_by column we could make all of them as 0. Maybe this is all is pre implemented in a function in fastai . Got to check that.

## Train_cats

In [343]:
train_cats(train_raw)

In [344]:
train_raw.impact.cat.set_categories(['3 - Low','2 - Medium','1 - High'],ordered=True,inplace=True)
train_raw.urgency.cat.set_categories(['3 - Low','2 - Medium','1 - High'],ordered=True,inplace=True)
train_raw.priority.cat.set_categories(train_raw.priority.cat.categories[::-1],ordered=True,inplace=True)

In [345]:
train_raw.isnull().sum().sort_index()/len(train_raw)

Id                           0.000000
assigned_to                  0.270962
category                     0.000906
contact_type                 0.000000
impact                       1.000000
knowledge                    0.000000
location                     0.001058
made_sla                     0.000000
notify                       0.000000
opened_atDay                 0.000000
opened_atDayofweek           0.000000
opened_atDayofyear           0.000000
opened_atElapsed             0.000000
opened_atIs_month_end        0.000000
opened_atIs_month_start      0.000000
opened_atIs_quarter_end      0.000000
opened_atIs_quarter_start    0.000000
opened_atIs_year_end         0.000000
opened_atIs_year_start       0.000000
opened_atMonth               0.000000
opened_atWeek                0.000000
opened_atYear                0.000000
opened_by                    0.029310
priority                     0.000000
reassignment_count           0.000000
reopen_count                 0.000000
subcategory                  0.001133
target_days                  0.000000
update_count                 0.000000
urgency                      1.000000
dtype: float64

# Preprocessing

In [346]:
def preprocessingl(df_raw):
    df = df_raw.copy()
    df.drop(columns=['Id'],inplace=True)
    add_datepart(df,'opened_at')
    extracting_num(df)
    return df

In [347]:
train_raw.T

,0,1,2,3,4,5,6,7,8,9,...,19987,19988,19990,19992,19993,19994,19995,19996,19997,19999
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062,INC0000063,INC0000064,INC0000065,INC0000066,INC0000067,...,INC0028185,INC0028186,INC0028188,INC0028191,INC0028192,INC0028193,INC0028195,INC0028196,INC0028200,INC0028203
reassignment_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reopen_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
update_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,8,397,8,180,180,180,131,131,24,180,...,24,24,24,131,62,24,17,17,24,55
contact_type,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,...,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone,Phone
location,143,165,204,204,93,93,143,108,161,143,...,161,43,161,161,143,108,204,93,97,204
category,55,40,20,9,53,20,53,44,55,9,...,26,26,9,42,53,20,42,37,42,26
subcategory,170,215,125,97,168,125,168,229,185,110,...,164,275,164,223,303,174,223,174,223,275
impact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
urgency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
priority,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
assigned_to,NaN,Resolver 89,NaN,Resolver 125,NaN,NaN,Resolver 78,Resolver 216,NaN,Resolver 236,...,Resolver 17,Resolver 17,Resolver 24,Resolver 194,Resolver 33,Resolver 93,Resolver 13,Resolver 83,Resolver 17,NaN
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,...,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify
target_days,5,6,5,7,5,5,8,7,7,7,...,5,5,6,5,5,6,5,5,5,5
opened_atYear,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,...,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
opened_atMonth,2,2,2,2,2,2,2,2,2,2,...,5,5,5,5,5,5,5,5,5,5
opened_atWeek,9,9,9,9,9,9,9,9,9,9,...,19,19,19,19,19,19,19,19,19,19
opened_atDay,29,29,29,29,29,29,29,29,29,29,...,11,11,11,11,11,11,11,11,11,11
opened_atDayofweek,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
opened_atDayofyear,60,60,60,60,60,60,60,60,60,60,...,132,132,132,132,132,132,132,132,132,132
opened_atIs_month_end,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_month_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atElapsed,1456708560,1456720800,1456726200,1456727880,1456729080,1456729680,1456729800,1456731480,1456732980,1456732980,...,1462955940,1462955940,1462956060,1462956120,1462956240,1462956240,1462956300,1462956360,1462956600,1462956720

## Data after preprocessing

In [348]:
display_all(train_raw.head().T)

,0,1,2,3,4
Id,INC0000045,INC0000047,INC0000057,INC0000060,INC0000062
reassignment_count,0,0,0,0,0
reopen_count,0,0,0,0,0
update_count,0,0,0,0,0
made_sla,True,True,True,True,True
opened_by,8,397,8,180,180
contact_type,Phone,Phone,Phone,Phone,Phone
location,143,165,204,204,93
category,55,40,20,9,53
subcategory,170,215,125,97,168
impact,NaN,NaN,NaN,NaN,NaN
urgency,NaN,NaN,NaN,NaN,NaN
priority,3,3,3,3,3
assigned_to,NaN,Resolver 89,NaN,Resolver 125,NaN
knowledge,True,True,True,True,True
notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify,Do Not Notify
target_days,5,6,5,7,5
opened_atYear,2016,2016,2016,2016,2016
opened_atMonth,2,2,2,2,2
opened_atWeek,9,9,9,9,9
opened_atDay,29,29,29,29,29
opened_atDayofweek,0,0,0,0,0
opened_atDayofyear,60,60,60,60,60
opened_atIs_month_end,True,True,True,True,True
opened_atIs_month_start,False,False,False,False,False
opened_atIs_quarter_end,False,False,False,False,False
opened_atIs_quarter_start,False,False,False,False,False
opened_atIs_year_end,False,False,False,False,False
opened_atIs_year_start,False,False,False,False,False
opened_atElapsed,1456708560,1456720800,1456726200,1456727880,1456729080

# Preparing model

In [349]:
train , y, nas = proc_df(train_raw,'target_days')

In [350]:
train.T

,0,1,2,3,4,5,6,7,8,9,...,19987,19988,19990,19992,19993,19994,19995,19996,19997,19999
Id,1,2,3,4,5,6,7,8,9,10,...,13229,13230,13231,13232,13233,13234,13235,13236,13237,13238
reassignment_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reopen_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
update_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,129,82,129,23,23,23,12,12,41,23,...,41,41,41,12,124,41,20,20,41,120
contact_type,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
location,31,42,76,76,169,169,31,5,40,31,...,40,129,40,40,31,5,76,169,172,76
category,35,24,5,42,33,5,33,28,35,42,...,10,10,42,26,33,5,26,21,26,10
subcategory,52,80,22,183,50,22,50,89,64,11,...,47,120,47,85,139,55,85,55,85,120
impact,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
urgency,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
priority,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
assigned_to,0,148,0,15,0,0,143,80,0,96,...,50,50,99,67,113,150,19,146,50,0
knowledge,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
notify,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
opened_atYear,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,...,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
opened_atMonth,2,2,2,2,2,2,2,2,2,2,...,5,5,5,5,5,5,5,5,5,5
opened_atWeek,9,9,9,9,9,9,9,9,9,9,...,19,19,19,19,19,19,19,19,19,19
opened_atDay,29,29,29,29,29,29,29,29,29,29,...,11,11,11,11,11,11,11,11,11,11
opened_atDayofweek,0,0,0,0,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,2,2
opened_atDayofyear,60,60,60,60,60,60,60,60,60,60,...,132,132,132,132,132,132,132,132,132,132
opened_atIs_month_end,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_month_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atElapsed,1456708560,1456720800,1456726200,1456727880,1456729080,1456729680,1456729800,1456731480,1456732980,1456732980,...,1462955940,1462955940,1462956060,1462956120,1462956240,1462956240,1462956300,1462956360,1462956600,1462956720

In [351]:
from sklearn import preprocessing

In [352]:
label_encoder = preprocessing.LabelEncoder()

In [353]:
train['made_sla']= label_encoder.fit_transform(train['made_sla'])

In [354]:
train['knowledge']= label_encoder.fit_transform(train['knowledge'])

In [355]:
train['opened_atIs_month_end']= label_encoder.fit_transform(train['opened_atIs_month_end'])

In [356]:
train['opened_atIs_month_start']= label_encoder.fit_transform(train['opened_atIs_month_start'])

In [357]:
train['opened_atIs_quarter_end']= label_encoder.fit_transform(train['opened_atIs_quarter_end'])

In [358]:
train['opened_atIs_quarter_start']= label_encoder.fit_transform(train['opened_atIs_quarter_start'])

In [359]:
train['opened_atIs_year_end']= label_encoder.fit_transform(train['opened_atIs_year_end'])

In [360]:
train['opened_atIs_year_start']= label_encoder.fit_transform(train['opened_atIs_year_start'])

In [361]:
n_valid = 3000 
n_trn = len(train) - n_valid
X_train , X_valid = split_vals(train,n_trn)
y_train , y_valid = split_vals(y,n_trn)

X_train.shape , X_valid.shape , y_train.shape , y_valid.shape

((10238, 29), (3000, 29), (10238,), (3000,))

In [362]:
m = RandomForestClassifier(n_jobs=-1,random_state=3,min_samples_leaf=1)
m.fit(X_train,y_train)

/home/vaibhav/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
                       oob_score=False, random_state=3, verbose=0,
                       warm_start=False)

In [363]:
print_score(m)

0.048251611642899005 0.588

In [364]:
xg_reg = xgb.XGBClassifier(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 50)

In [365]:
xg_reg.fit(X_train,y_train)

XGBClassifier(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.3, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=None, n_estimators=50, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [366]:
print_score(xg_reg)

0.5978706778667708 0.5446666666666666

In [367]:
from sklearn.neighbors import KNeighborsClassifier

In [368]:
n = KNeighborsClassifier()

In [369]:
n.fit(X_train,y_train)
print_score(n)

0.5712053135378004 0.5453333333333333

# TEST

In [370]:
Id = test_raw['Id']

In [371]:
test_raw = preprocessingl(test_raw)

In [372]:
apply_cats(test_raw,train_raw)

In [373]:
test,_,_=proc_df(test_raw)

In [374]:
test.shape , train.shape

((4918, 29), (13238, 29))

In [380]:
test.T

,0,1,2,3,4,5,6,7,8,9,...,4908,4909,4910,4911,4912,4913,4914,4915,4916,4917
reassignment_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
reopen_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
update_count,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
made_sla,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
opened_by,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
contact_type,2,2,2,2,2,2,2,2,2,2,...,0,0,0,0,0,1,0,2,1,1
location,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
category,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
subcategory,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
impact,2,2,2,2,2,2,2,2,2,2,...,1,1,1,1,1,2,1,2,2,2
urgency,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
priority,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
assigned_to,104,93,82,137,141,0,15,29,113,0,...,0,0,0,0,0,133,0,0,1,1
knowledge,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
notify,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
vendor,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
opened_atYear,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,...,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017
opened_atMonth,5,5,5,5,5,5,5,5,5,5,...,2,2,2,2,2,2,2,2,2,2
opened_atWeek,19,19,19,19,19,19,19,19,19,19,...,7,7,7,7,7,7,7,7,7,7
opened_atDay,11,11,11,11,11,11,11,11,11,11,...,13,14,14,14,15,15,15,15,16,16
opened_atDayofweek,2,2,2,2,2,2,2,2,2,2,...,0,1,1,1,2,2,2,2,3,3
opened_atDayofyear,132,132,132,132,132,132,132,132,132,132,...,44,45,45,45,46,46,46,46,47,47
opened_atIs_month_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_month_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_quarter_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_end,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atIs_year_start,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
opened_atElapsed,1462956720,1462956780,1462956900,1462957140,1462957140,1462957140,1462957200,1462957200,1462957260,1462957260,...,1486985460,1487070660,1487070900,1487097060,1487123520,1487124120,1487142540,1487159880,1487236140,1487254620

In [381]:
# test['made_sla']= label_encoder.fit_transform(test['made_sla'])
# test['knowledge']= label_encoder.fit_transform(test['knowledge'])
# test['opened_atIs_month_end']= label_encoder.fit_transform(test['opened_atIs_month_end'])
# test['opened_atIs_month_start']= label_encoder.fit_transform(test['opened_atIs_month_start'])
# test['opened_atIs_quarter_end']= label_encoder.fit_transform(test['opened_atIs_quarter_end'])
# test['opened_atIs_quarter_start']= label_encoder.fit_transform(test['opened_atIs_quarter_start'])
# test['opened_atIs_year_end']= label_encoder.fit_transform(test['opened_atIs_year_end'])
# test['opened_atIs_year_start']= label_encoder.fit_transform(test['opened_atIs_year_start'])

In [384]:
# test.drop(columns='vendor',inplace=True)

In [385]:
# y_testt = xg_reg.predict(test)

ValueError: feature_names mismatch: ['Id', 'reassignment_count', 'reopen_count', 'update_count', 'made_sla', 'opened_by', 'contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assigned_to', 'knowledge', 'notify', 'opened_atYear', 'opened_atMonth', 'opened_atWeek', 'opened_atDay', 'opened_atDayofweek', 'opened_atDayofyear', 'opened_atIs_month_end', 'opened_atIs_month_start', 'opened_atIs_quarter_end', 'opened_atIs_quarter_start', 'opened_atIs_year_end', 'opened_atIs_year_start', 'opened_atElapsed'] ['reassignment_count', 'reopen_count', 'update_count', 'made_sla', 'opened_by', 'contact_type', 'location', 'category', 'subcategory', 'impact', 'urgency', 'priority', 'assigned_to', 'knowledge', 'notify', 'opened_atYear', 'opened_atMonth', 'opened_atWeek', 'opened_atDay', 'opened_atDayofweek', 'opened_atDayofyear', 'opened_atIs_month_end', 'opened_atIs_month_start', 'opened_atIs_quarter_end', 'opened_atIs_quarter_start', 'opened_atIs_year_end', 'opened_atIs_year_start', 'opened_atElapsed']
expected Id in input data

In [ ]:
dict = {
    'Id':Id,
    'target_days':y_test
}

In [ ]:
submit = pd.DataFrame(dict)

In [ ]:
submit.to_csv('submit6.csv',header=True,index=False)